# Generated by Django 4.2.4 on 2023-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('midname', models.CharField(max_length=30)),
                ('institution', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
